### PR TITLE
Resolve Dialyzer errors on Elixir 1.16

### LINKED ISSUE #642: Dialyzer failing on Tesla (master)
Just cloned Tesla (commit 6388e3c) and ran `mix dialyzer` on Elixir 1.16.0.

The following output:

```
Finding suitable PLTs
Checking PLT...
Dialyxir has deprecated plt_add_deps: :project in favor of apps_direct, which includes only runtime dependencies.
** (ArgumentError) errors were found at the given arguments:

  * 2nd argument: not a tuple

    (erts 14.2.1) :erlang.element(1, :mime)
    (dialyxir 1.4.2) lib/dialyxir/project.ex:371: anonymous fn/1 in Dialyxir.Project.load_project_deps/1
    (elixir 1.16.0) lib/enum.ex:1700: Enum."-map/2-lists^map/1-1-"/2
    (elixir 1.16.0) lib/map.ex:262: Map.new_from_enum/2
    (dialyxir 1.4.2) lib/dialyxir/project.ex:371: Dialyxir.Project.load_project_deps/1
    (dialyxir 1.4.2) lib/dialyxir/project.ex:342: anonymous fn/2 in Dialyxir.Project.include_deps/0
    (dialyxir 1.4.2) lib/dialyxir/project.ex:321: Dialyxir.Project.include_deps/0
    (dialyxir 1.4.2) lib/dialyxir/project.ex:53: Dialyxir.Project.cons_apps/0
```

### PR DESCRIPTION
**Pull request by nathany-copia**
closes #642

This is to address this Dialyzer error seen in Elixir 1.16.

```
Total errors: 3, Skipped: 0, Unnecessary Skips: 0
done in 0m1.17s
lib/tesla/multipart.ex:94: Function add_file/2 has no local return
lib/tesla/multipart.ex:94: Function add_file/3 has no local return
lib/tesla/multipart.ex:106: The call 'Elixir.File':'stream!'(_path@1::binary() | maybe_improper_list(binary() | maybe_improper_list(any(),binary() | []) | char(),binary() | []),[],2048) breaks the contract ('Elixir.Path':t(),'line' | pos_integer(),[stream_mode()]) -> 'Elixir.File.Stream':t()
done (warnings were emitted)
Halting VM with exit status 2
```

Dialyzer is also added to CI as a separate job (it can be rather slow, and we may want to control success/failure independently for Dialyzer)

### CODE REVIEW

File: mix.exs [hunk 1]
```diff
@@ -10,15 +10,15 @@ defmodule Tesla.Mixfile do
...
-      elixir: "~> 1.10",
+      elixir: "~> 1.16",
       elixirc_paths: elixirc_paths(Mix.env()),
       deps: deps(),
       lockfile: lockfile(System.get_env("LOCKFILE")),
       test_coverage: [tool: ExCoveralls],
       dialyzer: [
         plt_core_path: "_build/#{Mix.env()}",
         plt_add_apps: [:mix, :inets, :idna, :ssl_verify_fun, :ex_unit],
-        plt_add_deps: :project
```
Comment (nathany-copia) [inline mix.exs:21]: the 2 options are here: https://github.com/jeremyjh/dialyxir?tab=readme-ov-file#dependencies

File: lib/tesla/multipart.ex [hunk 2]
```diff
@@ -103,7 +103,7 @@ defmodule Tesla.Multipart do
         false -> headers
       end
 
-    data = File.stream!(path, [], 2048)
```
Comment (nathany-copia) [inline lib/tesla/multipart.ex:106]: This changes resolves the dialyzer errors:

```
lib/tesla/multipart.ex:94: Function add_file/2 has no local return
lib/tesla/multipart.ex:94: Function add_file/3 has no local return
lib/tesla/multipart.ex:106: The call 'Elixir.File':'stream!'(_path@1::binary() | maybe_improper_list(binary() | maybe_improper_list(any(),binary() | []) | char(),binary() | []),[],2048) breaks the contract ('Elixir.Path':t(),'line' | pos_integer(),[stream_mode()]) -> 'Elixir.File.Stream':t()
```

But as mentioned in #642, I'm not sure how to make this change in a backwards compatible way. See the soft deprecations section of https://github.com/elixir-lang/elixir/releases/tag/v1.16.0

**Comment by nathany-copia** [comment]
FYI, I'm seeing a number of test failures locally -- on the `master` branch as well.

File: mix.exs [hunk 3]
```diff
@@ -10,15 +10,15 @@ defmodule Tesla.Mixfile do
       version: @version,
       description: description(),
       package: package(),
-      elixir: "~> 1.10",
+      elixir: "~> 1.16",
```
Comment (yordis) [inline mix.exs:13]: We can't make this such high jump for sure

File: lib/tesla/multipart.ex [hunk 4]
```diff
@@ -103,7 +103,7 @@ defmodule Tesla.Multipart do
...
+    data = File.stream!(path, 2048)
```
Comment (yordis) [inline lib/tesla/multipart.ex:106]:
```suggestion
    data = stream_file!(path, 2048)
```

Then later on somewhere in the module

```elixir
if Version.compare(System.version(), "1.16.0") do
  defp stream_file!(path, bytes), do: File.stream!(path, bytes)
else
    defp stream_file!(path, bytes), do: File.stream!(path, [], bytes)
end

Comment (nathany-copia) [reply lib/tesla/multipart.ex]: Thank you @yordis!

**Comment by nathany-copia** [comment]
@yordis Are there any other changes needed before we can merge this and publish a Tesla release that supports Elixir 1.16?

**Comment by yordis** [comment]
We need to add OTP 26 to the CI pipeline to make sure it is green

**Comment by nathany-copia** [comment]
CI updated.

I don't think we **need** any matrix exceptions based on the versions I saw over here, but I'm happy to make other changes.
https://github.com/ex-aws/ex_aws_s3/pull/239/files

Thanks.

**Comment by peaceful-james** [comment]
I am looking forward to this being merged :)

**Comment by nathany-copia** [comment]
Merged in master.

**Comment by yordis** [comment]
@nathany-copia could you use https://github.com/elixir-tesla/tesla/pull/623 as the baseline? Really appreciate your support here.

Related to https://github.com/edgurgel/httparrot/issues/38

The fix is in `httparrot` if I am not mistaken

**Comment by nathany-copia** [comment]
@yordis With Dialyzer passing on all versions, I hope we can review and merge this even without the httparrot issues fixed, as that would allow us to stop using a fork of Tesla.

File: .github/workflows/test.yml [hunk 5]
```diff
@@ -79,3 +83,65 @@ jobs:
...
+    # Doesn't cache PLTs based on mix.lock hash, as Dialyzer can incrementally update even old ones
+    # Cache key based on Elixir & Erlang version.
+    - name: Restore PLT cache
+      uses: actions/cache@v2
+      id: plt_cache
+      with:
+        key: |
+          ${{matrix.otp}}-${{ runner.os }}-${{ steps.beam.outputs.elixir-version }}-${{ steps.beam.outputs.otp-version }}-plt
+        restore-keys: |
+          ${{matrix.otp}}-${{ runner.os }}-${{ steps.beam.outputs.elixir-version }}-${{ steps.beam.outputs.otp-version }}-plt
```
Comment (nathany-copia) [inline .github/workflows/test.yml:139]: 🤔  I "borrowed" this from another project -- not sure why we were using both `matrix.otp` and `steps.beam.outputs.otp-version`

Comment (yordis) [reply .github/workflows/test.yml:139]: Always use `steps.beam.outputs.otp-version` across setups to avoid headaches. Probably it is OK to remove `matrix.otp` here

Comment (nathany-copia) [reply .github/workflows/test.yml]: okay. done!

File: .github/workflows/test.yml [hunk 6]
```diff
@@ -79,3 +83,65 @@ jobs:
       env:
         LOCKFILE: gun1
       run: mix test test/tesla/adapter/gun_test.exs --trace
+
+  dialyzer:
```
Comment (yordis) [inline .github/workflows/test.yml:87]: Run this only for the `main` matrix (maybe we should rename it from `lint` to `main_version` or something like that.

Comment (nathany-copia) [reply .github/workflows/test.yml:87]: So you just want to run it on a single version, such as Elixir 1.16 for now?

Are you also suggesting that this job is combined with the main Test job? I wouldn't recommend that, but I'll make the change if that's what you want.

**Comment by nathany-copia** [comment]
Please let me know if you'd like any other changes.

Thanks!

File: .github/workflows/test.yml (hunk 6 above)
Comment (yordis) [reply .github/workflows/test.yml:86]: > So you just want to run it on a single version,
Yes, no matrix setup

> I wouldn't recommend that

I do not have strong opinions, but I would like to hear your thoughts, so I can learn. Eitherway is fine by me

Comment (nathany-copia) [reply .github/workflows/test.yml:86]: Mainly that Dialyzer can be slow -- it takes 2 minutes to run, which is longer than the full test run. It's not so bad here on Tesla though, since it's a small library and not an entire application, but I think it's still nice to run them in parallel.

The other consideration is that this specific fix is for Dialyzer on Elixir 1.16, which we can see is passing. However, the standard test suite isn't yet passing on Elixir 1.16 due to httparrot.

So that may be a reason to keep them separate for now, even if we rather run them sequentially later on.

Comment (nathany-copia) [reply .github/workflows/test.yml:86]: matrix removed for dialyzer.

**Review by yordis — APPROVED** [review]
Really appreciate your support, thank you so much 🚀 💜

**Comment by yordis** [comment]
Hopefully we can figure out the elixir 1.6+ situation next 😭

**Comment by nathany-copia** [comment]
> Hopefully we can figure out the elixir 1.6+ situation next 😭

Absolutely. I already opened a pull request to httparrot, so we'll see how that goes.

@yordis We'd appreciate another hex release if you don't mind. ❤️ 

@peaceful-james I'll leave this branch here for a bit, just in case you're using it.

**Comment by peaceful-james** [comment]
@nathany-copia I am not using it but thank you.
